apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-replication-controller
  labels:
    environement: development
    group-owner: finance
  annotations:
    description: ini adalah replication controller punya team finance jadi kamu jangan macam-macam yah. I love u
spec:
  replicas: 3
  selector:
    group-owner: finance
  template:
    metadata:
      name: nginx-rc
      labels:
        environment: development
        group-owner: finance
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 5
            failureThreshold: 3
            successThreshold: 1
            timeoutSeconds: 5
