apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-rs
  labels:
    owner: finance-team
  annotations:
    description: ini adalah punya tim finance
spec:
  replicas: 3
  selector:
    matchLabels:
      owner: finance
  template:
    metadata:
      name: nginx-rs
      labels:
        owner: finance
    spec:
      containers:
        - name: nginx-rs
          image: nginx
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 3
            failureThreshold: 3
            successThreshold: 1
            timeoutSeconds: 1
