apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-rs-with-expression
  labels:
    owner: finance-team
  annotations:
    description: ini adalah punya tim finance
spec:
  replicas: 3
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
            - nginx
  template:
    metadata:
      name: nginx-rs
      labels:
        owner: finance
        app: nginx
    spec:
      containers:
        - name: nginx-rs
          image: nginx
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 3
            failureThreshold: 3
            successThreshold: 1
            timeoutSeconds: 1
